#!/usr/bin/env python3
"""
ESLint-style static analysis for the vanilla JS modules (lint_js.py)
====================================================================
LEARN: Static analysis without dependencies — regex-based checks that catch
the same class of bugs an ESLint rule set does, using only the Python
standard library so the project stays zero-pip.

Checks:
1. Syntax         — runs `node --check` on every module when Node is available.
2. Dead methods   — object methods defined but never referenced anywhere.
3. Unused globals — module-level `const`/`let`/`function` never referenced.
4. Orphan DOM ids — getElementById/querySelector('#x') targets that exist in
                    neither index.html nor any module's markup.
5. Duplicates     — the same module-level name declared twice in one file.
6. TODO markers   — counted as informational (not an error).

Usage:
    python3 scripts/lint_js.py          # full report, exit 1 on errors
    python3 scripts/lint_js.py --quiet  # errors only

Exit code 0 = clean, 1 = findings (CI fails on findings).
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JS_DIR = ROOT / "static" / "js"
INDEX_HTML = ROOT / "static" / "index.html"

# bundle.js is generated by scripts/build.py — never analyze it directly.
MODULES = sorted(p for p in JS_DIR.glob("*.js") if p.name != "bundle.js")

IDENT_RE = re.compile(r"\b([A-Za-z_$][A-Za-z0-9_$]*)\b")
MODULE_LEVEL_CONST_RE = re.compile(r"^(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)\b", re.M)
MODULE_LEVEL_FUNC_RE = re.compile(r"^(?:async\s+)?function\s+([A-Za-z_$][A-Za-z0-9_$]*)\b", re.M)
METHOD_RE = re.compile(r"^    (?:async\s+)?([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{", re.M)
METHOD_NAMED_FUNC_RE = re.compile(r"^    ([A-Za-z_$][A-Za-z0-9_$]*)\s*:\s*(?:async\s+)?function\b", re.M)

ID_REF_RE = re.compile(r"getElementById\(['\"]([A-Za-z0-9_-]+)['\"]\)")
ID_REF_Q_RE = re.compile(r"querySelector(?:All)?\(['\"]#([A-Za-z0-9_-]+)['\"]\)")
ID_DEF_RE = re.compile(r"id=['\"]([A-Za-z0-9_-]+)['\"]")
ID_ASSIGN_RE = re.compile(r"\.id\s*=\s*['\"]([A-Za-z0-9_-]+)['\"]")

TODO_RE = re.compile(r"\b(?:TODO|FIXME|HACK|XXX)\b", re.I)


def module_sources():
    """Returns {path: source} for every analyzable JS module."""
    return {p: p.read_text(encoding="utf-8") for p in MODULES}


def count_occurrences(name, texts):
    """Counts every bare-identifier occurrence of `name` across `texts`."""
    pattern = re.compile(rf"\b{re.escape(name)}\b")
    return sum(len(pattern.findall(t)) for t in texts)


def syntax_check(path):
    """Runs `node --check`; returns (ok, detail) or None when Node is missing."""
    try:
        res = subprocess.run(["node", "--check", str(path)],
                             capture_output=True, text=True, timeout=15)
    except (FileNotFoundError, subprocess.SubprocessError):
        return None
    detail = (res.stderr or res.stdout).strip().splitlines()
    return (res.returncode == 0, detail[-1] if detail else "syntax error")


def main():
    quiet = "--quiet" in sys.argv
    sources = module_sources()
    # Reference scope = every module + index.html (inline onclick="X.method()").
    scope_texts = list(sources.values()) + [INDEX_HTML.read_text(encoding="utf-8")]
    errors, infos = [], []

    # 1. Syntax
    for path in MODULES:
        result = syntax_check(path)
        if result is None:
            infos.append(f"{path.name}: `node --check` skipped (Node not installed)")
        elif not result[0]:
            errors.append(f"{path.name}: syntax error — {result[1]}")

    # 2. Dead object methods + 3. unused module-level names
    for path, source in sources.items():
        # Duplicate module-level declarations (check 5)
        decl_counts = {}
        for name in MODULE_LEVEL_CONST_RE.findall(source):
            decl_counts[name] = decl_counts.get(name, 0) + 1
        for name in MODULE_LEVEL_FUNC_RE.findall(source):
            decl_counts[name] = decl_counts.get(name, 0) + 1
        for name, count in sorted(decl_counts.items()):
            if count > 1:
                errors.append(f"{path.name}: '{name}' declared {count} times at module level")

        # Module-level names never referenced anywhere
        for name in MODULE_LEVEL_CONST_RE.findall(source):
            if count_occurrences(name, scope_texts) <= 1:
                errors.append(f"{path.name}: unused global '{name}' (declared but never used)")
        for name in MODULE_LEVEL_FUNC_RE.findall(source):
            if count_occurrences(name, scope_texts) <= 1:
                errors.append(f"{path.name}: unused function '{name}' (declared but never called)")

        # Object methods never referenced anywhere (definition counts as 1)
        for name in METHOD_RE.findall(source):
            if count_occurrences(name, scope_texts) <= 1:
                errors.append(f"{path.name}: dead method '{name}' (defined but never used)")
        for name in METHOD_NAMED_FUNC_RE.findall(source):
            if count_occurrences(name, scope_texts) <= 1:
                errors.append(f"{path.name}: dead method '{name}' (defined but never used)")

    # 4. Orphan DOM ids
    id_refs = set()
    for source in sources.values():
        id_refs.update(ID_REF_RE.findall(source))
        id_refs.update(ID_REF_Q_RE.findall(source))
    id_defs = set(ID_DEF_RE.findall(INDEX_HTML.read_text(encoding="utf-8")))
    for source in sources.values():
        id_defs.update(ID_DEF_RE.findall(source))
        id_defs.update(ID_ASSIGN_RE.findall(source))
    for name in sorted(id_refs - id_defs):
        errors.append(f"orphan DOM id '{name}' — referenced in JS but defined in no HTML")

    # 6. TODO markers (informational)
    todo_count = sum(len(TODO_RE.findall(s)) for s in sources.values())
    if todo_count and not quiet:
        infos.append(f"{todo_count} TODO/FIXME marker(s) in JS modules (informational)")

    if not quiet:
        for line in infos:
            print(f"[info] {line}")
    for line in errors:
        print(f"[error] {line}")

    if not errors:
        print("✓ No lint errors found.")
        return 0
    print(f"\n{len(errors)} error(s) found.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
